### ISSUE TITLE
Is it possible to use this in conjunction with with the okgrow:analytics package?

### ISSUE THREAD

**Issue by yanndebelgique** [astronomerio/meteor-events#1]
https://atmospherejs.com/okgrow/analytics
both use segment.io and I was wondering if this wouldn't cause an issue (i.e. events showing up as doubles in usercycle).

**Comment by ryw** [comment]
I'd say probably not — looks like both okgrow:analytics and this package do similar things. What's your use case to use them together, curious?

**Comment by yanndebelgique** [comment]
I want to track more than user retention. I'd like to track when they click on certain buttons etcetera. Ok now that I think of it I should just use the analytics object that exists already on the client since usercycle uses it and shoot additional events I might want to track. right?

**Comment by ryw** [comment]
We're deprecating this package in favor of https://github.com/astronomerio/meteor-astronomer
